update step in task 3
Step 3 produced an error:
ERROR: (gcloud.run.services.describe) argument (SERVICE : --namespace=NAMESPACE): Must be specified.

This is caused by $BILLING_SERVICE variable has not been set, I have added in line 33